---
- import_tasks: setup_repo.yml

- name: Install package
  ansible.builtin.apt:
    name: "tempo={{ grafana_tempo_version }}"
    state: "present"
    allow_downgrade: true
  
- name: Install certificate key
  ansible.builtin.copy:
    mode: '0600'
    owner: tempo
    group: nogroup
    dest: /etc/tempo/cert.key
    content: "{{ grafana_tempo_cert_key }}"
  when: grafana_tempo_cert_key is defined

- name Install certificate file
  ansible.builtin.copy:
    mode: '0600'
    owner: tempo
    group: nogroup
    dest: /etc/tempo/cert.file
    content: "{{ grafana_tempo_cert_file | mandatory }}"
  when: grafana_tempo_cert_key is defined

- name: Generate certificate
  ansible.builtin.include_tasks: generate_certs.yml
  vars:
    cert_key_path: /etc/tempo/cert.key
    cert_file_path: /etc/tempo/cert.file
    cert_owner: tempo
    cert_group: nogroup
  when: grafana_tempo_cert_key is undefined

- name: Configure
  ansible.builtin.template:
    src: templates/tempo_config.yml.j2
    dest: /etc/tempo/config.yml
    mode: 600
    owner: tempo
    group: nogroup

- name: Start service
  ansible.builtin.systemd:
    daemon-reload: yes
    enabled: true
    state: started
    name: tempo.service